app/app.py
from flask import Flask
from config import Configuration
from posts.blueprint import posts

app = Flask(__name__)
app.config.from_object(Configuration)
app.register_blueprint(posts, url_prefix='/blog')

app/main.py
from app import app
import views

if __name__ == '__main__':
    app.run()

app/posts/blueprint.py
from flask import Blueprint, render_template

posts = Blueprint('posts', __name__, template_folder='templates')


@posts.route('/')
def index():
    return render_template('posts/index.html')

app/views.py
from app import app
from flask import render_template

@app.route('/')
def index():
    name = 'shpak'
    return render_template('index.html', n=name)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>
        {% block title %}

        {% endblock %} | Flask blog
    </title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{ url_for('index') }}">Flask</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('posts.index') }}">Blog</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" action="#">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="query">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

<div class="container mt-3">
    <div class="row">
        {% block content %}

        {% endblock %}
    </div>
</div>

</body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block title %}
    Index Page
{% endblock %}

{% block content %}
    <h2>Index</h2>
{% endblock %}